name: test package
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      - develop
      - beta
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/dev.txt
          pip install -e .
      - name: Run
        run: |
          python -c "import pybss; print(pybss.__version__)"
          python -c "from pybss.bss import GradLaplaceIVA"
      - name: pytest
        run: |
          wget -P .data/ "https://www.iks.rwth-aachen.de/fileadmin/user_upload/downloads/forschung/tools-downloads/Impulse_response_Acoustic_Lab_Bar-Ilan_University__Reverberation_0.160s__8-8-8-8-8-8-8.zip"